In [1]:
import os
os.chdir("../../")

import pandas as pd
import numpy as np
from statsmodels.tsa.vector_ar.vecm import VECM
from statsmodels.tsa.vector_ar.vecm import select_order
from scripts.python.tsa.mtsmodel import *
from scripts.python.tsa.ts_eval import *

import warnings
warnings.filterwarnings("ignore")

In [2]:
test = VARPipeline(country="palau", data=None, 
                   var_name=["total", "seats_arrivals_intl"],
                   exog=["covid", "stringency_index", "covid"])
test.read_and_merge()
test.test_stationarity()
test.transform()
t_search = test.varma_search()

,date,seats_arrivals_total,seats_arrivals_intl,number_of_flights_total,number_of_flights_intl,japan,south_korea,taiwan,china,usa/canada,europe,others,total,stringency_index,covid,palau_flights,palau_hotel,palau_travel
0,2019-01-01,13048,13048,75,75,2055.0,1035.0,1092.0,4059.0,702.0,438.0,371.0,9752.0,0.0,0.0,0.493228,2.559978,0.194222
1,2019-02-01,13281,13281,74,74,2434.0,1090.0,1190.0,2549.0,826.0,483.0,461.0,9033.0,0.0,0.0,0.310671,2.841414,0.282245
2,2019-03-01,12870,12870,73,73,1756.0,808.0,1099.0,3182.0,777.0,368.0,415.0,8405.0,0.0,0.0,0.386389,2.921431,0.286529
3,2019-04-01,10806,10806,64,64,1288.0,1095.0,1393.0,2489.0,607.0,185.0,421.0,7478.0,0.0,0.0,0.293529,2.981907,0.338945
4,2019-05-01,11472,11472,67,67,650.0,655.0,1399.0,2321.0,622.0,119.0,305.0,6071.0,0.0,0.0,0.306351,3.537987,0.168664

order = 0: no stationarity obtained.

,Test Statistic,p-value,# Lags Used,Number of Observations Used,Critical Value (1%),Critical Value (5%),Critical Value (10%)
total,-2.752038,0.065458,5.0,37.0,-3.620918,-2.943539,-2.610400
seats_arrivals_intl,-5.394519,0.000003,0.0,42.0,-3.596636,-2.933297,-2.604991

order = 1: stationarity obtained.
 Running for {'p': 1, 'q': 1, 'tr': 'n'}
 Running for {'p': 1, 'q': 1, 'tr': 'c'}
 Running for {'p': 1, 'q': 1, 'tr': 't'}
 Running for {'p': 1, 'q': 1, 'tr': 'ct'}
 Running for {'p': 1, 'q': 2, 'tr': 'n'}
 Running for {'p': 1, 'q': 2, 'tr': 'c'}
 Running for {'p': 1, 'q': 2, 'tr': 't'}
 Running for {'p': 1, 'q': 2, 'tr': 'ct'}
 Running for {'p': 1, 'q': 3, 'tr': 'n'}
 Running for {'p': 1, 'q': 3, 'tr': 'c'}
 Running for {'p': 1, 'q': 3, 'tr': 't'}
 Running for {'p': 1, 'q': 3, 'tr': 'ct'}
 Running for {'p': 2, 'q': 1, 'tr': 'n'}
 Running for {'p': 2, 'q': 1, 'tr': 'c'}
 Running for {'p': 2, 'q': 1, 'tr': 't'}
 Running for {'p': 2, 'q': 1, 'tr': 'ct'}
 Running for {'p': 2, 'q': 2, 'tr': 'n'}
 Running for {'p': 2, 'q': 2, 'tr': 'c'}
 Running for {'p': 2, 'q': 2, 'tr': 't'}
 Running for {'p': 2, 'q': 2, 'tr': 'ct'}
 Running for {'p': 2, 'q': 3, 'tr': 'n'}
 Running for {'p': 2, 'q': 3, 'tr': 'c'}
 Running for {'p': 2, 'q': 3, 'tr': 't'}
 Running for {'p': 2, 'q': 3, 'tr': 'ct'}
 Running for {'p': 3, 'q': 1, 'tr': 'n'}
 Running for {'p': 3, 'q': 1, 'tr': 'c'}
 Running for {'p': 3, 'q': 1, 'tr': 't'}
 Running for {'p': 3, 'q': 1, 'tr': 'ct'}
 Running for {'p': 3, 'q': 2, 'tr': 'n'}
 Running for {'p': 3, 'q': 2, 'tr': 'c'}
 Running for {'p': 3, 'q': 2, 'tr': 't'}
 Running for {'p': 3, 'q': 2, 'tr': 'ct'}
 Running for {'p': 3, 'q': 3, 'tr': 'n'}
 Running for {'p': 3, 'q': 3, 'tr': 'c'}
 Running for {'p': 3, 'q': 3, 'tr': 't'}
 Running for {'p': 3, 'q': 3, 'tr': 'ct'}

In [47]:
from statsmodels.tsa.api import VARMAX
mod = VARMAX(test.data[["total", "seats_arrivals_intl"]],
             exog=test.data[test.exog],
             order=(1, 3),
             trend="c").fit(disp=False)

print(calculate_evaluation(test.data["total"], naive_method(test.data["total"])))
print(calculate_evaluation(test.data["total"], mod.fittedvalues["total"]))

{'MSE': 1192288.1395348837, 'RMSE': 1091.9194748400103, 'MAE': 636.8837209302326, 'SMAPE': 54.46121058732388}
{'MSE': 730352.211616988, 'RMSE': 854.6064659344604, 'MAE': 694.8881523051377, 'SMAPE': 86.16022388069882}

In [22]:
test.transform()

In [32]:
scaled = pd.DataFrame([test.x1_trans, test.x2_trans]).T
display(get_adf_df(scaled, ["total", "seats_arrivals_intl"]))

from sklearn.model_selection import ParameterGrid
param_grid = {'p': [1, 2, 3],
              'q': [1, 2, 3],
              'tr': ['n', 'c', 't', 'ct']}
pg = list(ParameterGrid(param_grid))

model_res = {
    "model": [],
    "result": []
}

for idx, params in enumerate(pg):
    print(f' Running for {params}')
    p = params.get('p')
    q = params.get('q')
    tr = params.get('tr')
    model = VARMAX(scaled,
                   exog=test.data[test.exog],
                   order=(p, q),
                   trend=tr).fit(disp=False)
    model_res["model"].append((p, q, tr))
    model_res["result"].append(model.aic)

,Test Statistic,p-value,# Lags Used,Number of Observations Used,Critical Value (1%),Critical Value (5%),Critical Value (10%)
total,-2.497021,0.116201,2.0,41.0,-3.600983,-2.935135,-2.605963
seats_arrivals_intl,-2.837020,0.053177,2.0,41.0,-3.600983,-2.935135,-2.605963

 Running for {'p': 1, 'q': 1, 'tr': 'n'}
 Running for {'p': 1, 'q': 1, 'tr': 'c'}
 Running for {'p': 1, 'q': 1, 'tr': 't'}
 Running for {'p': 1, 'q': 1, 'tr': 'ct'}
 Running for {'p': 1, 'q': 2, 'tr': 'n'}
 Running for {'p': 1, 'q': 2, 'tr': 'c'}
 Running for {'p': 1, 'q': 2, 'tr': 't'}
 Running for {'p': 1, 'q': 2, 'tr': 'ct'}
 Running for {'p': 1, 'q': 3, 'tr': 'n'}
 Running for {'p': 1, 'q': 3, 'tr': 'c'}
 Running for {'p': 1, 'q': 3, 'tr': 't'}
 Running for {'p': 1, 'q': 3, 'tr': 'ct'}
 Running for {'p': 2, 'q': 1, 'tr': 'n'}
 Running for {'p': 2, 'q': 1, 'tr': 'c'}
 Running for {'p': 2, 'q': 1, 'tr': 't'}
 Running for {'p': 2, 'q': 1, 'tr': 'ct'}
 Running for {'p': 2, 'q': 2, 'tr': 'n'}
 Running for {'p': 2, 'q': 2, 'tr': 'c'}
 Running for {'p': 2, 'q': 2, 'tr': 't'}
 Running for {'p': 2, 'q': 2, 'tr': 'ct'}
 Running for {'p': 2, 'q': 3, 'tr': 'n'}
 Running for {'p': 2, 'q': 3, 'tr': 'c'}
 Running for {'p': 2, 'q': 3, 'tr': 't'}
 Running for {'p': 2, 'q': 3, 'tr': 'ct'}
 Running for {'p': 3, 'q': 1, 'tr': 'n'}
 Running for {'p': 3, 'q': 1, 'tr': 'c'}
 Running for {'p': 3, 'q': 1, 'tr': 't'}
 Running for {'p': 3, 'q': 1, 'tr': 'ct'}
 Running for {'p': 3, 'q': 2, 'tr': 'n'}
 Running for {'p': 3, 'q': 2, 'tr': 'c'}
 Running for {'p': 3, 'q': 2, 'tr': 't'}
 Running for {'p': 3, 'q': 2, 'tr': 'ct'}
 Running for {'p': 3, 'q': 3, 'tr': 'n'}
 Running for {'p': 3, 'q': 3, 'tr': 'c'}
 Running for {'p': 3, 'q': 3, 'tr': 't'}
 Running for {'p': 3, 'q': 3, 'tr': 'ct'}

In [43]:
mod_scaled = VARMAX(scaled,
             exog=test.data[test.exog],
             order=(1, 2),
             trend="t").fit(disp=False)

fit_revs = []
for val in mod.fittedvalues["total"]:
    rev_val = inverse_scaledlogit(val, test.data["total"].max()+1, test.data["total"].min()-1)
    fit_revs.append(rev_val)

In [45]:
calculate_evaluation(test.data["total"], fit_revs)

{'MSE': 1865480.8635396196,
 'RMSE': 1365.8260736783507,
 'MAE': 774.9586152686217,
 'SMAPE': 55.81115325036844}

In [17]:
endog = test.data[["seats_arrivals_intl", "total"]]
exog = test.data[["covid", "stringency_index", "palau_travel"]]

# Determine the optimal lag order using the information criterion
lag_order = select_order(endog, maxlags=10, exog=exog)

# Create a VECM model with the selected lag order
model = VECM(endog, k_ar_diff=lag_order.selected_orders['aic'], exog=exog)

# Fit the VECM model
results = model.fit()

# Print the estimated parameters
print(results.summary())

# Get the long-run relationships (cointegrating vectors)
print(results.coint_rank)

# Perform Granger causality tests
granger_test = results.test_granger_causality(caused=1, causing=0)
print(granger_test.summary())

Det. terms outside the coint. relation & lagged endog. parameters for equation seats_arrivals_intl
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
exog1                       3.5720   1118.633      0.003      0.997   -2188.909    2196.053
exog2                      -9.8641     17.907     -0.551      0.582     -44.961      25.233
exog3                    2098.2777   1361.566      1.541      0.123    -570.342    4766.898
L1.seats_arrivals_intl     -0.5823      0.220     -2.652      0.008      -1.013      -0.152
L1.total                    0.9613      0.173      5.567      0.000       0.623       1.300
L2.seats_arrivals_intl     -0.3897      0.318     -1.225      0.220      -1.013       0.234
L2.total                    1.0455      0.436      2.398      0.016       0.191       1.900
L3.seats_arrivals_intl     -0.1287      0.246     -0.524      0.600      -0.610       0.353
L3.total                    1.3373      0.343      3.896      0.000       0.665       2.010
L4.seats_arrivals_intl     -0.4568      0.251     -1.819      0.069      -0.949       0.035
L4.total                   -0.3203      0.481     -0.666      0.506      -1.263       0.623
L5.seats_arrivals_intl     -0.6224      0.270     -2.304      0.021      -1.152      -0.093
L5.total                    1.1274      0.418      2.696      0.007       0.308       1.947
L6.seats_arrivals_intl     -0.3563      0.256     -1.394      0.163      -0.857       0.145
L6.total                    0.8935      0.589      1.517      0.129      -0.261       2.048
L7.seats_arrivals_intl     -0.1726      0.349     -0.495      0.621      -0.856       0.511
L7.total                    0.3546      0.431      0.823      0.410      -0.490       1.199
L8.seats_arrivals_intl      0.0360      0.216      0.167      0.867      -0.387       0.459
L8.total                    0.8963      0.556      1.611      0.107      -0.194       1.987
L9.seats_arrivals_intl      0.1008      0.204      0.495      0.621      -0.299       0.500
L9.total                    0.0791      0.425      0.186      0.852      -0.754       0.912
L10.seats_arrivals_intl     0.0162      0.036      0.447      0.655      -0.055       0.087
L10.total                  -0.4449      0.734     -0.607      0.544      -1.883       0.993
    Det. terms outside the coint. relation & lagged endog. parameters for equation total
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
exog1                   -5349.9735    863.557     -6.195      0.000   -7042.514   -3657.433
exog2                      81.6957     13.824      5.910      0.000      54.602     108.790
exog3                    4645.3421   1051.095      4.420      0.000    2585.235    6705.450
L1.seats_arrivals_intl      0.3023      0.169      1.784      0.074      -0.030       0.634
L1.total                    0.8542      0.133      6.408      0.000       0.593       1.115
L2.seats_arrivals_intl      1.5040      0.246      6.126      0.000       1.023       1.985
L2.total                    1.3256      0.337      3.939      0.000       0.666       1.985
L3.seats_arrivals_intl      0.4314      0.190      2.276      0.023       0.060       0.803
L3.total                   -1.9889      0.265     -7.506      0.000      -2.508      -1.470
L4.seats_arrivals_intl     -0.2504      0.194     -1.292      0.197      -0.630       0.130
L4.total                   -1.6697      0.371     -4.495      0.000      -2.398      -0.942
L5.seats_arrivals_intl     -0.1974      0.209     -0.946      0.344      -0.606       0.211
L5.total                    0.2120      0.323      0.657      0.511      -0.421       0.845
L6.seats_arrivals_intl      0.5692      0.197      2.885      0.004       0.182       0.956
L6.total                    0.8808      0.455      1.937      0.053      -0.010       1.772
L7.seats_arrivals_intl      1.3552      0.269      5.032      0.000       0.827       1.883
L7.total                   -1.1606      0.332     -3.491      0.000      -1.812      -0.509
L8.seats_arrivals_intl      0.9437      0.167      5.662      0.000       0.617       1.270
L8.total                   -1.3203      0.429     -3.074      0.002      -2.162      -0.479
L9.seats_arrivals_intl      0.7097      0.157      4.509      0.000       0.401       1.018
L9.total                   -1.6147      0.328     -4.921      0.000      -2.258      -0.972
L10.seats_arrivals_intl    -0.0301      0.028     -1.076      0.282      -0.085       0.025
L10.total                  -2.7030      0.566     -4.773      0.000      -3.813      -1.593
        Loading coefficients (alpha) for equation seats_arrivals_intl
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ec1            0.0098      0.062      0.159      0.874      -0.111       0.130
               Loading coefficients (alpha) for equation total
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ec1            0.3643      0.047      7.671      0.000       0.271       0.457
          Cointegration relations for loading-coefficients-column 1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
beta.1         1.0000          0          0      0.000       1.000       1.000
beta.2        -5.0610      0.195    -26.006      0.000      -5.442      -4.680
==============================================================================
1
Granger causality F-test. H_0: seats_arrivals_intl does not Granger-cause total. Conclusion: reject H_0 at 5% significance level.
==============================================
Test statistic Critical value p-value    df
----------------------------------------------
         53.90          2.943   0.000 (11, 10)
----------------------------------------------

In [18]:
calculate_evaluation(endog["total"], pd.DataFrame(results.fittedvalues)[1])

{'MSE': 19006337.115832955,
 'RMSE': 4359.625799977901,
 'MAE': 2870.2403678881547,
 'SMAPE': 143.58928425671743}